// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	btp "github.com/kyma-project/auditlog-manager/internal/btp"

	mock "github.com/stretchr/testify/mock"
)

// BTPClient is an autogenerated mock type for the BTPClient type
type BTPClient struct {
	mock.Mock
}

type BTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *BTPClient) EXPECT() *BTPClient_Expecter {
	return &BTPClient_Expecter{mock: &_m.Mock}
}

// CreateLoggingStack provides a mock function with given fields: ctx, tenantID
func (_m *BTPClient) CreateLoggingStack(ctx context.Context, tenantID string) error {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoggingStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BTPClient_CreateLoggingStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLoggingStack'
type BTPClient_CreateLoggingStack_Call struct {
	*mock.Call
}

// CreateLoggingStack is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *BTPClient_Expecter) CreateLoggingStack(ctx interface{}, tenantID interface{}) *BTPClient_CreateLoggingStack_Call {
	return &BTPClient_CreateLoggingStack_Call{Call: _e.mock.On("CreateLoggingStack", ctx, tenantID)}
}

func (_c *BTPClient_CreateLoggingStack_Call) Run(run func(ctx context.Context, tenantID string)) *BTPClient_CreateLoggingStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BTPClient_CreateLoggingStack_Call) Return(_a0 error) *BTPClient_CreateLoggingStack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BTPClient_CreateLoggingStack_Call) RunAndReturn(run func(context.Context, string) error) *BTPClient_CreateLoggingStack_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubaccount provides a mock function with given fields: ctx, region, globalAccountID, displayName, administrators
func (_m *BTPClient) CreateSubaccount(ctx context.Context, region string, globalAccountID string, displayName string, administrators []string) (string, error) {
	ret := _m.Called(ctx, region, globalAccountID, displayName, administrators)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubaccount")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (string, error)); ok {
		return rf(ctx, region, globalAccountID, displayName, administrators)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) string); ok {
		r0 = rf(ctx, region, globalAccountID, displayName, administrators)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = rf(ctx, region, globalAccountID, displayName, administrators)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BTPClient_CreateSubaccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubaccount'
type BTPClient_CreateSubaccount_Call struct {
	*mock.Call
}

// CreateSubaccount is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - globalAccountID string
//   - displayName string
//   - administrators []string
func (_e *BTPClient_Expecter) CreateSubaccount(ctx interface{}, region interface{}, globalAccountID interface{}, displayName interface{}, administrators interface{}) *BTPClient_CreateSubaccount_Call {
	return &BTPClient_CreateSubaccount_Call{Call: _e.mock.On("CreateSubaccount", ctx, region, globalAccountID, displayName, administrators)}
}

func (_c *BTPClient_CreateSubaccount_Call) Run(run func(ctx context.Context, region string, globalAccountID string, displayName string, administrators []string)) *BTPClient_CreateSubaccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *BTPClient_CreateSubaccount_Call) Return(_a0 string, _a1 error) *BTPClient_CreateSubaccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BTPClient_CreateSubaccount_Call) RunAndReturn(run func(context.Context, string, string, string, []string) (string, error)) *BTPClient_CreateSubaccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLoggingStack provides a mock function with given fields: ctx, tenantID
func (_m *BTPClient) DeleteLoggingStack(ctx context.Context, tenantID string) error {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLoggingStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BTPClient_DeleteLoggingStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLoggingStack'
type BTPClient_DeleteLoggingStack_Call struct {
	*mock.Call
}

// DeleteLoggingStack is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *BTPClient_Expecter) DeleteLoggingStack(ctx interface{}, tenantID interface{}) *BTPClient_DeleteLoggingStack_Call {
	return &BTPClient_DeleteLoggingStack_Call{Call: _e.mock.On("DeleteLoggingStack", ctx, tenantID)}
}

func (_c *BTPClient_DeleteLoggingStack_Call) Run(run func(ctx context.Context, tenantID string)) *BTPClient_DeleteLoggingStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BTPClient_DeleteLoggingStack_Call) Return(_a0 error) *BTPClient_DeleteLoggingStack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BTPClient_DeleteLoggingStack_Call) RunAndReturn(run func(context.Context, string) error) *BTPClient_DeleteLoggingStack_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubaccount provides a mock function with given fields: ctx, subaccountGUID
func (_m *BTPClient) DeleteSubaccount(ctx context.Context, subaccountGUID string) error {
	ret := _m.Called(ctx, subaccountGUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubaccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, subaccountGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BTPClient_DeleteSubaccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubaccount'
type BTPClient_DeleteSubaccount_Call struct {
	*mock.Call
}

// DeleteSubaccount is a helper method to define mock.On call
//   - ctx context.Context
//   - subaccountGUID string
func (_e *BTPClient_Expecter) DeleteSubaccount(ctx interface{}, subaccountGUID interface{}) *BTPClient_DeleteSubaccount_Call {
	return &BTPClient_DeleteSubaccount_Call{Call: _e.mock.On("DeleteSubaccount", ctx, subaccountGUID)}
}

func (_c *BTPClient_DeleteSubaccount_Call) Run(run func(ctx context.Context, subaccountGUID string)) *BTPClient_DeleteSubaccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BTPClient_DeleteSubaccount_Call) Return(_a0 error) *BTPClient_DeleteSubaccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BTPClient_DeleteSubaccount_Call) RunAndReturn(run func(context.Context, string) error) *BTPClient_DeleteSubaccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubaccount provides a mock function with given fields: ctx, subaccountGUID
func (_m *BTPClient) GetSubaccount(ctx context.Context, subaccountGUID string) (bool, string, error) {
	ret := _m.Called(ctx, subaccountGUID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubaccount")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, string, error)); ok {
		return rf(ctx, subaccountGUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, subaccountGUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, subaccountGUID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, subaccountGUID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BTPClient_GetSubaccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubaccount'
type BTPClient_GetSubaccount_Call struct {
	*mock.Call
}

// GetSubaccount is a helper method to define mock.On call
//   - ctx context.Context
//   - subaccountGUID string
func (_e *BTPClient_Expecter) GetSubaccount(ctx interface{}, subaccountGUID interface{}) *BTPClient_GetSubaccount_Call {
	return &BTPClient_GetSubaccount_Call{Call: _e.mock.On("GetSubaccount", ctx, subaccountGUID)}
}

func (_c *BTPClient_GetSubaccount_Call) Run(run func(ctx context.Context, subaccountGUID string)) *BTPClient_GetSubaccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BTPClient_GetSubaccount_Call) Return(exists bool, state string, err error) *BTPClient_GetSubaccount_Call {
	_c.Call.Return(exists, state, err)
	return _c
}

func (_c *BTPClient_GetSubaccount_Call) RunAndReturn(run func(context.Context, string) (bool, string, error)) *BTPClient_GetSubaccount_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyLoggingStack provides a mock function with given fields: ctx, tenantID
func (_m *BTPClient) VerifyLoggingStack(ctx context.Context, tenantID string) (btp.InstallStatus, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyLoggingStack")
	}

	var r0 btp.InstallStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (btp.InstallStatus, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) btp.InstallStatus); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(btp.InstallStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BTPClient_VerifyLoggingStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyLoggingStack'
type BTPClient_VerifyLoggingStack_Call struct {
	*mock.Call
}

// VerifyLoggingStack is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *BTPClient_Expecter) VerifyLoggingStack(ctx interface{}, tenantID interface{}) *BTPClient_VerifyLoggingStack_Call {
	return &BTPClient_VerifyLoggingStack_Call{Call: _e.mock.On("VerifyLoggingStack", ctx, tenantID)}
}

func (_c *BTPClient_VerifyLoggingStack_Call) Run(run func(ctx context.Context, tenantID string)) *BTPClient_VerifyLoggingStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BTPClient_VerifyLoggingStack_Call) Return(_a0 btp.InstallStatus, _a1 error) *BTPClient_VerifyLoggingStack_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BTPClient_VerifyLoggingStack_Call) RunAndReturn(run func(context.Context, string) (btp.InstallStatus, error)) *BTPClient_VerifyLoggingStack_Call {
	_c.Call.Return(run)
	return _c
}

// NewBTPClient creates a new instance of BTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BTPClient {
	mock := &BTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
