with-expecter: true
dir: "internal/btp/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
inpackage: false
testonly: false

# Deprecation fixes for v3 compatibility
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/kyma-project/auditlog-manager/internal/btp:
    interfaces:
      BTPClient:
