---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - auditlogmanager.kyma-project.io
  resources:
  - auditlogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auditlogmanager.kyma-project.io
  resources:
  - auditlogs/finalizers
  verbs:
  - update
- apiGroups:
  - auditlogmanager.kyma-project.io
  resources:
  - auditlogs/status
  verbs:
  - get
  - patch
  - update
